version: '3'
services:
  traefik:
    image: traefik:v1.7.9
    command: --docker
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json"
    environment:
      - DO_AUTH_TOKEN
    networks:
      - default
